### ISSUE TITLE
[QUESTION] Does it work with new newest uasset file Format (UE5 5.0.2)

### ISSUE THREAD

**Issue by NewSkyLineTwitter** [matyalatte/Blender-Uasset-Addon#1]
Just a little question if this blender addon works with the newest .uasset file format. 
:)

**Comment by matyalatte** [comment]
Won't work for now.
But I'll add support for the standard UE versions in the future.

**Comment by matyalatte** [comment]
Hi, I started to support UE5 at [v0.1.5](https://github.com/matyalatte/Blender-Uasset-Addon/releases/tag/v0.1.5).
But I only tested it with the default mannequins.
So, I'd appriciate it if you could share your assets for testing.
If you can, please send the files to me with [Discord](https://discord.gg/Qx2Ff3MByF) or [Twitter](https://twitter.com/MatyaModding)

**Comment by matyalatte** [comment]
Static mesh support at [v0.1.6](https://github.com/matyalatte/Blender-Uasset-Addon/releases/tag/v0.1.6).
I'll close this issue because there are no replies.
You can reopen it if you have any questions.
